"""Tests for bin/smart_commit.py."""

import os
from unittest.mock import call, patch

import pytest

from bin.smart_commit import (
    _strip_fences,
    build_prompt,
    call_claude,
    do_commit,
    find_claude,
    get_staged_diff,
    main,
    stage_all,
)


class TestFindClaude:
    def test_uses_cli_arg_first(self):
        with patch.dict(os.environ, {"CLAUDE_PATH": "/env/claude"}):
            with patch("bin.smart_commit.shutil.which", return_value="/which/claude"):
                assert find_claude("/arg/claude") == "/arg/claude"

    def test_uses_env_var_when_no_arg(self):
        with patch.dict(os.environ, {"CLAUDE_PATH": "/env/claude"}):
            with patch("bin.smart_commit.shutil.which", return_value="/which/claude"):
                assert find_claude(None) == "/env/claude"

    def test_falls_back_to_which(self):
        env = {k: v for k, v in os.environ.items() if k != "CLAUDE_PATH"}
        with patch.dict(os.environ, env, clear=True):
            with patch("bin.smart_commit.shutil.which", return_value="/which/claude"):
                assert find_claude(None) == "/which/claude"

    def test_returns_none_when_not_found(self):
        env = {k: v for k, v in os.environ.items() if k != "CLAUDE_PATH"}
        with patch.dict(os.environ, env, clear=True):
            with patch("bin.smart_commit.shutil.which", return_value=None):
                assert find_claude(None) is None


class TestGetStagedDiff:
    def test_returns_diff_on_success(self):
        with patch("bin.smart_commit.run_command", return_value=(0, "diff text", "")) as mock_rc:
            rc, diff, err = get_staged_diff("/repo")
            assert rc == 0
            assert diff == "diff text"
            mock_rc.assert_called_once_with(["git", "diff", "--staged"], cwd="/repo")

    def test_returns_error_on_failure(self):
        with patch("bin.smart_commit.run_command", return_value=(128, "", "not a git repo")):
            rc, _, stderr = get_staged_diff("/repo")
            assert rc == 128
            assert "not a git repo" in stderr


class TestStageAll:
    def test_calls_git_add(self):
        with patch("bin.smart_commit.run_command", return_value=(0, "", "")) as mock_rc:
            stage_all("/repo")
            mock_rc.assert_called_once_with(["git", "add", "-A"], cwd="/repo")

    def test_returns_failure_on_nonzero(self):
        with patch("bin.smart_commit.run_command", return_value=(1, "", "some error")):
            rc, _, stderr = stage_all("/repo")
            assert rc == 1
            assert "some error" in stderr


class TestBuildPrompt:
    def test_contains_diff(self):
        diff = "--- a/foo.py\n+++ b/foo.py\n@@ -1 +1 @@ some change"
        prompt = build_prompt(diff)
        assert diff in prompt

    def test_no_attribution_keywords(self):
        prompt = build_prompt("some diff")
        lower = prompt.lower()
        assert "generated by" not in lower
        assert "anthropic" not in lower

    def test_imperative_rule_present(self):
        prompt = build_prompt("diff")
        assert "imperative" in prompt.lower()

    def test_no_fence_rule_present(self):
        prompt = build_prompt("diff")
        assert "fences" in prompt.lower() or "markdown" in prompt.lower()


class TestCallClaude:
    def test_passes_prompt_as_p_flag(self):
        with patch("bin.smart_commit.run_command", return_value=(0, "Add feature", "")) as mock_rc:
            call_claude("/usr/bin/claude", "my prompt", "/repo")
            args = mock_rc.call_args[0][0]
            assert args[0] == "/usr/bin/claude"
            assert "-p" in args
            assert "my prompt" in args

    def test_passes_output_format_text(self):
        with patch("bin.smart_commit.run_command", return_value=(0, "msg", "")) as mock_rc:
            call_claude("/usr/bin/claude", "prompt", "/repo")
            args = mock_rc.call_args[0][0]
            assert "--output-format" in args
            assert "text" in args

    def test_uses_120s_timeout(self):
        with patch("bin.smart_commit.run_command", return_value=(0, "msg", "")) as mock_rc:
            call_claude("/usr/bin/claude", "prompt", "/repo")
            assert mock_rc.call_args[1]["timeout"] == 120

    def test_failure_propagates(self):
        with patch("bin.smart_commit.run_command", return_value=(1, "", "API error")):
            rc, _, stderr = call_claude("/usr/bin/claude", "prompt", "/repo")
            assert rc == 1
            assert "API error" in stderr


class TestStripFences:
    def test_strips_fenced_code_block(self):
        text = "```\nFix the bug\n```"
        assert _strip_fences(text) == "Fix the bug"

    def test_strips_fenced_with_language(self):
        text = "```text\nAdd feature\n\nBody here\n```"
        assert _strip_fences(text) == "Add feature\n\nBody here"

    def test_leaves_plain_text_alone(self):
        text = "Fix the login flow"
        assert _strip_fences(text) == text

    def test_leaves_single_line_alone(self):
        text = "```only one fence"
        assert _strip_fences(text) == text


class TestDoCommit:
    def test_calls_git_commit_with_message(self):
        with patch("bin.smart_commit.run_command", return_value=(0, "[main abc123]", "")) as mock_rc:
            do_commit("/repo", "Fix the bug")
            mock_rc.assert_called_once_with(
                ["git", "commit", "-m", "Fix the bug"], cwd="/repo"
            )

    def test_returns_failure_on_nonzero(self):
        with patch("bin.smart_commit.run_command", return_value=(1, "", "hook failed")):
            rc, _, stderr = do_commit("/repo", "msg")
            assert rc == 1
            assert "hook failed" in stderr


class TestMain:
    def _run(self, argv, **patches):
        """Run main() with all subprocess calls patched."""
        defaults = {
            "find_claude": "/usr/bin/claude",
            "stage_all": (0, "", ""),
            "get_staged_diff": (0, "diff content", ""),
            "call_claude": (0, "Fix the bug", ""),
            "do_commit": (0, "[main abc]", ""),
        }
        defaults.update(patches)

        with patch("bin.smart_commit.find_claude", return_value=defaults["find_claude"]), \
             patch("bin.smart_commit.stage_all", return_value=defaults["stage_all"]), \
             patch("bin.smart_commit.get_staged_diff", return_value=defaults["get_staged_diff"]), \
             patch("bin.smart_commit.call_claude", return_value=defaults["call_claude"]), \
             patch("bin.smart_commit.do_commit", return_value=defaults["do_commit"]):
            return main(argv)

    def test_no_staged_changes_exits_0(self):
        rc = self._run([], get_staged_diff=(0, "", ""))
        assert rc == 0

    def test_claude_not_found_exits_1(self):
        rc = self._run([], find_claude=None)
        assert rc == 1

    def test_stage_all_failure_exits_1(self):
        rc = self._run(["--stage-all"], stage_all=(1, "", "permission denied"))
        assert rc == 1

    def test_git_diff_failure_exits_1(self):
        rc = self._run([], get_staged_diff=(128, "", "not a repo"))
        assert rc == 1

    def test_claude_failure_exits_1(self):
        rc = self._run([], call_claude=(1, "", "timed out"))
        assert rc == 1

    def test_claude_empty_output_exits_1(self):
        rc = self._run([], call_claude=(0, "   ", ""))
        assert rc == 1

    def test_dry_run_does_not_commit(self):
        with patch("bin.smart_commit.find_claude", return_value="/usr/bin/claude"), \
             patch("bin.smart_commit.get_staged_diff", return_value=(0, "diff", "")), \
             patch("bin.smart_commit.call_claude", return_value=(0, "Fix bug", "")), \
             patch("bin.smart_commit.do_commit") as mock_commit:
            rc = main(["--dry-run"])
            assert rc == 0
            mock_commit.assert_not_called()

    def test_successful_commit_returns_0(self):
        rc = self._run([])
        assert rc == 0

    def test_commit_failure_exits_1(self):
        rc = self._run([], do_commit=(1, "", "pre-commit hook failed"))
        assert rc == 1

    def test_stage_all_then_empty_diff_exits_0(self):
        rc = self._run(["--stage-all"], stage_all=(0, "", ""), get_staged_diff=(0, "", ""))
        assert rc == 0

    def test_verbose_prints_diff(self, capsys):
        self._run(["-v"])
        captured = capsys.readouterr()
        assert "diff content" in captured.out

    def test_stage_all_calls_stage(self):
        with patch("bin.smart_commit.find_claude", return_value="/usr/bin/claude"), \
             patch("bin.smart_commit.stage_all", return_value=(0, "", "")) as mock_stage, \
             patch("bin.smart_commit.get_staged_diff", return_value=(0, "diff", "")), \
             patch("bin.smart_commit.call_claude", return_value=(0, "Fix bug", "")), \
             patch("bin.smart_commit.do_commit", return_value=(0, "", "")):
            main(["--stage-all"])
            mock_stage.assert_called_once()

    def test_uses_cwd_by_default(self):
        with patch("bin.smart_commit.find_claude", return_value="/usr/bin/claude"), \
             patch("bin.smart_commit.get_staged_diff", return_value=(0, "diff", "")) as mock_diff, \
             patch("bin.smart_commit.call_claude", return_value=(0, "Fix bug", "")), \
             patch("bin.smart_commit.do_commit", return_value=(0, "", "")):
            main([])
            assert mock_diff.call_args[0][0] == os.getcwd()
